### ISSUE TITLE
Training -n nersc_ parameter not recognised 

### ISSUE THREAD

**Issue by Alissa13777** [nansencenter/DL-satellite#17]
When lauching training, using the "-n nersc_" as an entry parameter gives the following error:
![Screenshot (46)](https://user-images.githubusercontent.com/64470775/120347249-67907680-c2fc-11eb-9951-320d2fe20147.png)

**Comment by azamifarda** [comment]
@Alissa13777 
The training process of Tensorflow is working the npz files that stored beforehand. The noise method is previously selected to build that npz files. There is no need to give the error type in argument. The main of parameter that are used in training process are chosen in train_model.py file:
![image](https://user-images.githubusercontent.com/62345618/120441925-60fa1180-c385-11eb-8222-01f385226ee3.png)

**Comment by akorosov** [comment]
I guess this comes from misunderstanding of the readme file. @azamifarda , can you please split the table with params into three parts: agrs for build_dataset, args for train_model, args for apply_model? Let there be some duplication - that will be more clear than a single table.

**Comment by azamifarda** [comment]
OK I will do it, but I have written before how to find which one is which exactly after the table ends in README file:
![image](https://user-images.githubusercontent.com/62345618/120763608-ae0ded00-c517-11eb-83a1-6c8179faa8b9.png)

**Comment by azamifarda** [comment]
I have updated the README by separation of tables.
